services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: baran-db
      POSTGRES_USER: baran-user
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend-network

  backend:
    build: .
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/baran-db
      SPRING_DATASOURCE_USERNAME: baran-user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:?err}
#     SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge